### ISSUE TITLE
carla-2.0_beta5_p1[qt5] still builds with pyqt4 support

### ISSUE THREAD

**Issue by vthriller** [simonvanderveldt/simonvanderveldt-overlay#27]
```
$ carla
Traceback (most recent call last):
  File "/usr/share/carla/carla", line 22, in <module>
    from carla_host import *
  File "/usr/share/carla/carla_host.py", line 32, in <module>
    from PyQt4.QtCore import qCritical, QFileInfo, QModelIndex, QPointF, QTimer
ModuleNotFoundError: No module named 'PyQt4'
```

```
$ grep Qt5 /usr/share/carla/carla_config.py 
config_UseQt5 = False
```

```
$ equery u carla | grep qt5
+qt5
```

```
# grep Front carla-2.0_beta5_p1:20180225-045201.log
Front-End:    YES (Using Qt4)
```

**Comment by simonvanderveldt** [comment]
Hmm, interesting. Seems like at the very least `HAVE_QT5` is missing https://github.com/falkTX/Carla/blob/1.9.7b/Makefile#L22

But what I don't get is why it behaves as if `DEFAULT_QT` is set to 4, that's definitely not in the build, so no clue where that's coming from.
`DEFAULT_QT` is being used, among other things for the string in `carla_config.py`, see
https://github.com/falkTX/Carla/blob/1.9.7b/Makefile#L316

**Comment by vthriller** [comment]
> Seems like at the very least `HAVE_QT5` is missing

It definitely isn't:

```
---> LV2 UI toolkit support: 
…
Qt4:      YES (bridge)
Qt5:      YES (bridge)
```
```
Compiling CarlaStyle.cpp (Qt5)
…
Compiling resources.cpp (Qt5)
```

After some digging through Carla's `source/Makefile.mk` I can see why this is happening:
* [PyQt[45] are tested by just checking whether `/usr/bin/pyuic[45]` exist](https://github.com/falkTX/Carla/blob/1.9.7b/source/Makefile.mk#L261-L276). This is fine most of the time, but not in my case: I do actually have PyQt4 installed, but only for `python_targets_python2_7` (because <s>laziness</s> `package.use` was updated semi-automatically during `emerge picard`), and my default python version is 3.6. (Still that's just a weird corner case that, I guess, isn't worth any effort, or, at the very least, is not a point of this issue, but is something to be aware of.)
* Then [`DEFAULT_QT` just defaults to 4 if not overridden _and_ if PyQt4 is perceived as present](https://github.com/falkTX/Carla/blob/1.9.7b/source/Makefile.mk#L281-L285). `DEFAULT_QT` being _[whatever]_ is definitely not something I would expect from package with `qt5` use flag, and since it is set with `?=` this should be really very easy to fix.

**Comment by simonvanderveldt** [comment]
@vthriller FYI the carla package has been moved to the audio-overlay, you can find it here https://github.com/gentoo-audio/audio-overlay/tree/master/media-sound/carla

I checked a bunch of combinations to try and fix this issue and I believe it should all be working correctly with Qt5 now.
If you still run into issue can you create an issue there?
Sorry it took so long btw.
